CREATE USER 'fhdbased'@'localhost' IDENTIFIED BY '***';

GRANT ALL PRIVILEGES ON * . * TO 'fhdbased'@'localhost' IDENTIFIED BY '***' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `fhdbased` ;

GRANT ALL PRIVILEGES ON `fhdbased` . * TO 'fhdbased'@'localhost';
